//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Event
    {
        public int Id { get; set; }
        public string EventName { get; set; }
        public string Place { get; set; }
        public string Image { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime Date { get; set; }
    }
}
