//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Individual_Donor
    {
        public int Id { get; set; }
        public string DonorName { get; set; }
        [Display(Name = "Blood Group")]
        public int bid { get; set; }
        [Display(Name = "Gender")]
        public int gid { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime DOB { get; set; }
        [Display(Name = "State")]
        public int fkstateid { get; set; }
        public string PhoneNo { get; set; }
        public string AadharCardNo { get; set; }
        public bool IsActive { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime CreatedTime { get; set; }
        [Display(Name = "Email Id")]
        public string fk_id { get; set; }
        public string fk_roleid { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Blood_Gp Blood_Gp { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual State State { get; set; }
    }
}
