//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodDonationManagementSystem
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Org_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Org_details()
        {
            this.Donors = new HashSet<Donor>();
            this.Messages = new HashSet<Message>();
            this.Org_roles = new HashSet<Org_roles>();
        }
    
        public int pk_orgid { get; set; }
        [Display(Name = "Organization Name")]
        public string org_name { get; set; }
        [Display(Name = "Description")]
        public string org_descp { get; set; }
        [Display(Name = "Organization Email")]
        public string fk_id { get; set; }
        [Display(Name = "State")]
        public int fk_stateid { get; set; }
        [Display(Name = "Image")]
        public string org_image { get; set; }
        public bool IsActive { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Registered On")]
        public System.DateTime created_date { get; set; }
        public string fk_roleid { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Donor> Donors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Messages { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Org_roles> Org_roles { get; set; }
    }
}
